import {
  Controller,
  Get,
  Post,
  Put,
  Param,
  Query,
  Body,
  Request,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiOkResponse,
  ApiCreatedResponse,
  ApiBearerAuth,
  ApiParam,
  ApiQuery,
  ApiNotFoundResponse,
} from '@nestjs/swagger';
import { ComplianceService } from './compliance.service';

@ApiTags('compliance')
@ApiBearerAuth()
@Controller('compliance')
export class ComplianceController {
  constructor(private readonly complianceService: ComplianceService) {}

  @Get('aml/alerts')
  @ApiOperation({
    summary: 'List AML alerts',
    description:
      'Returns AML/CFT alerts generated by transaction monitoring rules. Requires compliance officer role.',
  })
  @ApiQuery({ name: 'status', required: false, enum: ['OPEN', 'INVESTIGATING', 'RESOLVED', 'ESCALATED'] })
  @ApiQuery({ name: 'severity', required: false, enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] })
  @ApiQuery({ name: 'page', required: false, type: Number })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiOkResponse({ description: 'AML alerts returned' })
  async getAlerts(
    @Query('status') status?: string,
    @Query('severity') severity?: string,
    @Query('page') page = 1,
    @Query('limit') limit = 20,
  ) {
    return this.complianceService.getAlerts({ status, severity, page, limit });
  }

  @Get('aml/alerts/:id')
  @ApiOperation({
    summary: 'Get AML alert details',
    description: 'Returns detailed information about a specific AML alert including related transactions.',
  })
  @ApiParam({ name: 'id', description: 'Alert UUID' })
  @ApiOkResponse({ description: 'Alert details returned' })
  @ApiNotFoundResponse({ description: 'Alert not found' })
  async getAlert(@Param('id') id: string) {
    return this.complianceService.getAlert(id);
  }

  @Put('aml/alerts/:id/status')
  @ApiOperation({
    summary: 'Update AML alert status',
    description: 'Updates the status of an AML alert (e.g. mark as investigating, resolve, escalate).',
  })
  @ApiParam({ name: 'id', description: 'Alert UUID' })
  @ApiOkResponse({ description: 'Alert status updated' })
  async updateAlertStatus(
    @Request() req: any,
    @Param('id') id: string,
    @Body() dto: { status: string; notes?: string },
  ) {
    return this.complianceService.updateAlertStatus(id, dto.status, dto.notes, req.user?.id);
  }

  @Post('sanctions/screen')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Screen against sanctions lists',
    description:
      'Screens a name or entity against BCEAO, UN, EU, and OFAC sanctions lists. Returns match results.',
  })
  @ApiOkResponse({ description: 'Screening results returned' })
  async screenSanctions(
    @Body() dto: { fullName: string; dateOfBirth?: string; nationality?: string },
  ) {
    return this.complianceService.screenSanctions(dto);
  }

  @Get('audit-logs')
  @ApiOperation({
    summary: 'Get audit logs',
    description:
      'Returns paginated audit trail of significant system events (logins, transactions, KYC changes, etc.).',
  })
  @ApiQuery({ name: 'userId', required: false, description: 'Filter by user ID' })
  @ApiQuery({ name: 'action', required: false, description: 'Filter by action type' })
  @ApiQuery({ name: 'from', required: false, description: 'Start date (ISO 8601)' })
  @ApiQuery({ name: 'to', required: false, description: 'End date (ISO 8601)' })
  @ApiQuery({ name: 'page', required: false, type: Number })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiOkResponse({ description: 'Audit logs returned' })
  async getAuditLogs(
    @Query('userId') userId?: string,
    @Query('action') action?: string,
    @Query('from') from?: string,
    @Query('to') to?: string,
    @Query('page') page = 1,
    @Query('limit') limit = 50,
  ): Promise<any> {
    return this.complianceService.getAuditLogs({ userId, action, from, to, page, limit });
  }

  @Post('audit-logs')
  @ApiOperation({
    summary: 'Create an audit log entry',
    description: 'Records a new audit log entry. Typically called internally by other services.',
  })
  @ApiCreatedResponse({ description: 'Audit log entry created' })
  async createAuditLog(
    @Body()
    dto: {
      userId?: string;
      action: string;
      entityType: string;
      entityId?: string;
      details?: Record<string, any>;
      ipAddress?: string;
    },
  ) {
    return this.complianceService.createAuditLog(dto);
  }

  @Get('reports/ctr')
  @ApiOperation({
    summary: 'Generate Currency Transaction Report',
    description:
      'Generates a CTR for transactions above the BCEAO reporting threshold (15M XOF).',
  })
  @ApiQuery({ name: 'from', required: true, description: 'Start date' })
  @ApiQuery({ name: 'to', required: true, description: 'End date' })
  @ApiOkResponse({ description: 'CTR report generated' })
  async generateCTR(@Query('from') from: string, @Query('to') to: string) {
    return this.complianceService.generateCTR(from, to);
  }
}
